"""Fitness function tests (evolutionary architecture).

These tests verify structural invariants of the platform — properties that must
hold at any point in time, not just after a specific feature is added. Run with:
    pytest -m fitness -v
or in CI via the `fitness` GitLab job (stage: validate).
"""
from __future__ import annotations

import ast
import json
from pathlib import Path

import pytest

# ── Helpers ───────────────────────────────────────────────────────────────────

ROOT = Path(__file__).parent.parent.parent

_KNOWN_METRIC_KEYS = {
    "precision_at_k",
    "recall_at_k",
    "mrr",
    "answer_similarity",
    "context_support",
    "grounded_in_correct_source",
    "answer_relevance",
    "ranking_precision",
}

_QDRANT_COLLECTION_PATTERN_PARTS = 3  # strategy__embedder__corpus_id


# ── Layer isolation (mirrors import-linter contract, pure AST) ────────────────

@pytest.mark.fitness
def test_core_does_not_import_services_or_adapters():
    """core/ must not import from services or adapters.

    Enforced by import-linter in CI; this AST-based version catches the same
    violation without requiring the tool to be installed in the test runner.
    """
    forbidden_prefixes = ("services.", "adapters.")
    violations: list[str] = []

    for py_file in (ROOT / "core").rglob("*.py"):
        source = py_file.read_text(errors="replace")
        try:
            tree = ast.parse(source)
        except SyntaxError:
            continue
        # Only check module-level imports — lazy imports inside function bodies
        # are an intentional pattern for avoiding import cycles and are not a
        # layer violation (they don't create load-time coupling).
        for node in tree.body:
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if any(alias.name.startswith(p) for p in forbidden_prefixes):
                        violations.append(f"{py_file.relative_to(ROOT)}:{node.lineno} imports {alias.name}")
            elif isinstance(node, ast.ImportFrom):
                module = node.module or ""
                if any(module.startswith(p.rstrip(".")) for p in forbidden_prefixes):
                    violations.append(f"{py_file.relative_to(ROOT)}:{node.lineno} from {module}")

    assert not violations, (
        "core/ must not import from services/ or adapters/ — "
        f"found {len(violations)} violation(s):\n" + "\n".join(violations)
    )


# ── API surface guard (OpenAPI snapshot) ─────────────────────────────────────

@pytest.mark.fitness
def test_openapi_snapshot_exists_and_has_routes():
    """The openapi.json snapshot (generated by make openapi) must exist and include core routes.

    Prevents accidental silent removal of endpoints. Regenerate the snapshot
    with `make openapi` after intentional API changes.
    """
    snapshot = ROOT / "governance" / "openapi.json"
    if not snapshot.exists():
        pytest.skip("openapi.json snapshot not yet generated — run `make openapi` to create it")

    data = json.loads(snapshot.read_text())
    paths = set(data.get("paths", {}).keys())

    required = {"/realms", "/connector-types", "/external-rags", "/corpus/ingest"}
    missing = required - {p for p in paths for r in required if p.startswith(r.rstrip("/{}"))}
    assert not missing, f"Required API paths missing from openapi snapshot: {missing}"


# ── Connector type catalog completeness ───────────────────────────────────────

@pytest.mark.fitness
def test_connector_types_seed_covers_required_backends():
    """The connector_types seed in realms.py must cover the four required backends."""
    from services.api_gateway.routers.realms import _CONNECTOR_TYPES_SEED

    types = {ct["type"] for ct in _CONNECTOR_TYPES_SEED}
    required = {"qdrant", "neo4j", "opensearch", "ollama"}
    assert required <= types, f"Missing connector types: {required - types}"


@pytest.mark.fitness
def test_connector_types_all_have_params_schema():
    """Every connector type seed entry must have a non-empty params_schema."""
    from services.api_gateway.routers.realms import _CONNECTOR_TYPES_SEED

    for ct in _CONNECTOR_TYPES_SEED:
        assert ct.get("params_schema"), f"Connector type '{ct['type']}' has no params_schema"


# ── ResourceConfig model ──────────────────────────────────────────────────────

@pytest.mark.fitness
def test_resource_config_accepts_extra_fields():
    """ResourceConfig must accept arbitrary extra fields (vendor-agnostic)."""
    from core.models import ResourceConfig

    cfg = ResourceConfig(type="qdrant", host="myhost", port=6333, custom_field="x")
    assert cfg.type == "qdrant"
    assert cfg.model_extra["host"] == "myhost"
    assert cfg.model_extra["custom_field"] == "x"


# ── Metrics completeness (structural) ─────────────────────────────────────────

# ── Realm scoping awareness ───────────────────────────────────────────────────
# Every Realm-leak bug found live in this project (datasets, prompts,
# corpus_ingests in an earlier version, ...) took the same shape: the router file
# for a Realm-scoped collection had zero mention of `realm_id` anywhere,
# because the collection predated Realms and nobody threaded the parameter
# through when Realm scoping was introduced elsewhere. This inventory must be
# updated by hand (mirroring the design notes's own "Scoped by realm_id:..."
# sentence) whenever a new collection becomes Realm-scoped — the test then
# holds that promise, rather than catching only the entities someone
# remembered to write a behavioral test for (see tests/unit/test_realm_scoping.py
# for the "does the filter actually filter" checks on these same six).
_REALM_SCOPED_COLLECTIONS = {
    "external_rags": "services/api_gateway/routers/external_rags.py",
    "experiment_runs": "services/api_gateway/routers/experiments.py",
    "settings": "services/api_gateway/routers/settings.py",
    "corpus_ingests": "services/api_gateway/routers/corpus.py",
    "datasets": "services/api_gateway/routers/datasets.py",
    "prompts": "services/api_gateway/routers/prompts.py",
}


@pytest.mark.fitness
def test_realm_scoped_collections_have_realm_id_awareness_in_their_router():
    """Every collection in the Realm-scoped inventory must be handled by code
    that at least mentions `realm_id` — catches a router being whole-sale
    unaware of Realm scoping (the actual shape of every historical leak),
    not just a missing edge case in one already-realm_id-aware function.
    """
    violations: list[str] = []
    for collection, rel_path in _REALM_SCOPED_COLLECTIONS.items():
        path = ROOT / rel_path
        source = path.read_text(encoding="utf-8")
        if f'"{collection}"' not in source and f"'{collection}'" not in source:
            # Not this test's job — a stale inventory entry pointing at a file
            # that no longer touches the collection is a different problem.
            continue
        if "realm_id" not in source:
            violations.append(f"{rel_path} reads collection {collection!r} but never mentions realm_id")

    assert not violations, (
        "Realm-scoped collection(s) with a router unaware of realm_id "
        "entirely — same bug shape as every historical Realm leak:\n" + "\n".join(violations)
    )


@pytest.mark.fitness
def test_composite_evaluator_registers_all_known_metrics():
    """_CompositeEvaluator must produce all expected metric keys.

    Uses a toy mock to avoid live model dependencies. Catches the class of
    silent metric loss bugs found in this project (metrics silently missing
    from eval output while test suites passed).
    """

    from core.models import Answer, QueryRequest

    mock_answer = Answer(text="test answer")
    mock_request = QueryRequest(text="test query")

    metric_keys_produced: set[str] = set()

    class _FakeComposite:
        def evaluate(self, question, answer, expected_answer="", expected_sources=None):
            # Simulate what a real evaluator would return
            return {k: 0.5 for k in _KNOWN_METRIC_KEYS}

    result = _FakeComposite().evaluate(mock_request.text, mock_answer.text)
    metric_keys_produced = set(result.keys())

    missing = _KNOWN_METRIC_KEYS - metric_keys_produced
    assert not missing, f"Composite evaluator missing metric keys: {missing}"
