/* The mark.
 *
 * Three variants were designed and one is in use. They are all here because the
 * choice between them is a matter of taste that ought to be inspectable rather
 * than argued from description, and because a mark that only exists as one
 * committed file cannot be compared with the alternatives it beat.
 *
 * Every variant obeys the same three constraints, which is what makes them
 * comparable at all:
 *   — legible at 16 px, where the sidebar actually renders it;
 *   — one colour, taken from `currentColor`, so it follows the palette;
 *   — no text inside the mark, so the wordmark can be set in any typeface.
 */

export type LogoVariant = 'cascade' | 'notch' | 'fan' | 'aperture'

/** The variant in use. Named, not inlined, so switching it is one edit. */
export const LOGO_VARIANT: LogoVariant = 'cascade'

/* ── cascade — three bars narrowing downward ──
 * The chosen mark. A funnel drawn as three steps: everything that was
 * retrieved, what survived reranking, what reached the answer. It is the
 * same shape the run page draws as `.funnel`, so the mark states what the
 * platform measures instead of alluding to it. The narrowing, not the
 * colour, carries the meaning, and it survives being one colour at 16 px.
 *
 * The steps are square modules on the grid the sibling registry's mark is
 * built from, module to pitch as 0.8. The kinship is carried by the unit of
 * measure instead of by a shared palette, so each mark keeps its own colour.
 *
 * The middle column takes the accent instead of `currentColor`, which is the
 * one departure from the constraint above and the reason for it: narrowing
 * alone read as a tree or an arrow, and what the funnel is about is the part
 * that came through. The accent is a palette token, so the mark still follows
 * the theme; it is a second colour, not a fixed one.
 *
 * The fading opacity the bars used to carry is gone. It doubled what the
 * narrowing already said, and at 16 px on a light ground the last step at
 * 0.34 was close to absent, against the very constraint it sat under.
 *
 * The coordinates come from `tools/mark_layout.py` and are generated by
 * `tools/build_mark.py`. Edit them there, not here.
 */
function Cascade({ size }: { size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <rect x="0.48" y="5.28" width="3.84" height="3.84" fill="currentColor" />
      <rect x="5.28" y="5.28" width="3.84" height="3.84" fill="currentColor" />
      <rect x="14.88" y="5.28" width="3.84" height="3.84" fill="currentColor" />
      <rect x="19.68" y="5.28" width="3.84" height="3.84" fill="currentColor" />
      <rect x="10.08" y="5.28" width="3.84" height="3.84" fill="var(--color-primary)" />
      <rect x="5.28" y="10.08" width="3.84" height="3.84" fill="currentColor" />
      <rect x="14.88" y="10.08" width="3.84" height="3.84" fill="currentColor" />
      <rect x="10.08" y="10.08" width="3.84" height="3.84" fill="var(--color-primary)" />
      <rect x="10.08" y="14.88" width="3.84" height="3.84" fill="var(--color-primary)" />
    </svg>
  )
}

/* ── notch — a disc with a wedge missing ──
 * The cause is the piece that is not there. A full disc says "everything is
 * accounted for"; the missing wedge is what the platform exists to name. Reads
 * as a single silhouette at 16 px, which the other two only just manage. */
function Notch({ size }: { size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true">
      {/* Disc with a 60° wedge cut from the upper right, drawn as one path so
          the counter stays crisp when the icon is scaled down. */}
      <path
        d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 10-10h-10z"
        fill="currentColor"
      />
      <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="1.6" opacity="0.45" />
      <circle cx="12" cy="12" r="2.4" fill="currentColor" opacity="0.35" />
    </svg>
  )
}

/* ── fan — one point, three diverging rays ──
 * The shape of the root-cause diagram: one verdict splits into several causes.
 * The most literal of the three about what the platform does. */
function Fan({ size }: { size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <circle cx="4.5" cy="12" r="2.6" fill="currentColor" />
      <path d="M7.4 11.2 19 4.6M7.4 12H19M7.4 12.8 19 19.4"
            stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" />
      <circle cx="20.4" cy="4" r="1.5" fill="currentColor" opacity="0.55" />
      <circle cx="20.4" cy="12" r="1.5" fill="currentColor" />
      <circle cx="20.4" cy="20" r="1.5" fill="currentColor" opacity="0.55" />
    </svg>
  )
}

/* ── aperture — a C that closes on a point ──
 * A monogram for Causa that also reads as a lens stopping down on one spot.
 * The most abstract, and the most typographic of the three. */
function Aperture({ size }: { size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M19.5 6.2A9 9 0 1 0 19.5 17.8"
        stroke="currentColor" strokeWidth="2.4" strokeLinecap="round"
      />
      <circle cx="12" cy="12" r="2.8" fill="currentColor" />
    </svg>
  )
}

const VARIANTS: Record<LogoVariant, (p: { size: number }) => JSX.Element> = {
  cascade: Cascade, notch: Notch, fan: Fan, aperture: Aperture,
}

export function LogoMark({ size = 18, variant = LOGO_VARIANT }: {
  size?: number; variant?: LogoVariant
}) {
  const Mark = VARIANTS[variant]
  return <Mark size={size} />
}

/** Mark plus wordmark, as the sidebar header uses it. */
export function Logo({ variant = LOGO_VARIANT }: { variant?: LogoVariant }) {
  return (
    <span className="brand">
      <span className="brand-mark"><LogoMark size={20} variant={variant} /></span>
      <span className="brand-word">
        Causa<span className="brand-word-accent">RAG</span>
      </span>
    </span>
  )
}
